name: ArmutSMP Modunu Derle

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v4

      - name: Java 21 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Gradle kur
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.2.0'

      - name: Modu derle
        run: gradle build

      - name: JAR dosyasini yukle
        uses: actions/upload-artifact@v4
        with:
          name: ArmutSMP-Dupe-Mod
          path: build/libs/*.jar
